### ISSUE TITLE
building kraken

### ISSUE THREAD

**Issue by ghost** [Limvot/kraken#4]
Hello   Limvot!

Kraken is an amazing looking language and I want to try it out but I can't build the self hosted compiler. I tried captain.sh script and also compiled depreciated compiler in c++ in order to compile kraken.krak. Did not go well.  Also do you intend to support 'for i in list' kind of for loop syntax in the future?

**Comment by Limvot** [comment]
Hello!
It's really cool that you're checking it out; how did you happen upon it?

To my chagrin, you're absolutely right. I messed up the chain of versions needed to bootstrap properly in the last few days. I've fixed it now, but to make sure it works you might have to delete all the binaries it's made so far, the cached_builds folder, and the bootstrap_kalypso folder. That's a lot to have to rebuild, so I've also attached my cached_builds folder [cached_builds.zip](https://github.com/Limvot/kraken/files/1793587/cached_builds.zip) that you should be able to drop in so it only has to build a couple of times, as well as a kraken.krak.c [kraken.krak.c.zip](https://github.com/Limvot/kraken/files/1793588/kraken.krak.c.zip) built from master, with master, so that you can just "cc -g -O2 -Wno-int-to-pointer-cast -Wno-pointer-to-int-cast -Wno-incompatible-pointer-types -std=c99 -lm  kraken.krak.c -o kraken" it to get started even faster, if you want.


Let me know if you have any other questions! Unfortunately, my documentation is in a pretty terrible state, but http://kraken-lang.org/ should be a decent walkthrough, though running the code online is broken right now as I re-write my interpreter 0.0 (I'll try to get an older version running tonight)

**Comment by selflex** [comment]
Awesome! I managed to build with cached_builds.zip file. And kraken binary compiles a simple hello world program as it should. I will try to do more with Kraken and see how far I can go. I stumbled upon Kraken when  I was searching for programming languages on Github. I am impressed by how simple and clean syntax Kraken has so I couldn't wait to build programs with it.  One thing I wonder is if you can define constants or is not required at all.

Thanks for your help and keep up the good work!

**Comment by Limvot** [comment]
Fantastic! Thank you very much - I've got big plans, (seamless C FFI, more powerful compile time code evaluation), so we'll see how it develops.

There's nothing for constants right now, when I need one I normally just make it a global variable. That would be a good addition.

Sure, and I'll try!

**Comment by arabelladonna** [comment]
What are the updated instructions for this? I tried running `captain.sh` in Mingw64 and Powershell (I'm on Windows) and it throws a bunch of errors from Git about committing or stashing changes before pushing them.

**Comment by Limvot** [comment]
Hi arabelladonna! Did you try with a full git clone and the cached_builds directory from the above linked zip in the main folder?

**Comment by arabelladonna** [comment]
Indeed I did. I've attached the full Mingw64 log, including attempting to build the old `kraken.krak.c` from master.

[krakenlog.txt](https://github.com/Limvot/kraken/files/4396302/krakenlog.txt)

**Comment by arabelladonna** [comment]
I realized that it was expecting `cached_builds` to be a directory up from where it was, but moving it did not allow it to build properly.

**Comment by Limvot** [comment]
Thank you! It might take me a bit to getting around to debugging it on Windows, it's not my normal dev environment

, but I've attached the latest generated kraken.krak.c file from my dev machine.
[kraken.krak.c.zip](https://github.com/Limvot/kraken/files/4396317/kraken.krak.c.zip)

**Comment by arabelladonna** [comment]
I just got around to trying it.

I get this error when attempting it.

```
D:/Applications/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/9.3.0/../../../../x86_64-w64-mingw32/bin/ld.exe: D:\Applications\msys64\tmp\ccQBTkdx.o:kraken.krak.c:(.rdata$.refptr.stdin[.refptr.stdin]+0x0): undefined reference to `stdin'
D:/Applications/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/9.3.0/../../../../x86_64-w64-mingw32/bin/ld.exe: D:\Applications\msys64\tmp\ccQBTkdx.o:kraken.krak.c:(.rdata$.refptr.stderr[.refptr.stderr]+0x0): undefined reference to `stderr'
collect2.exe: error: ld returned 1 exit status
```

Same error in the MSYS2 terminal, which has additional layers of Linux compatibility.

**Comment by Limvot** [comment]
Huh, that's odd! I wonder if that's a windows specific thing, I can try it later.

**Comment by Limvot** [comment]
No longer relevant now that I'm working on the new version bootstrapping from Chicken Scheme.
